export enum ResponseActionKeys {
  VERIFY_USER_EMAIL = 'VERIFY_USER_EMAIL',
  CLEAR_USER_SESSION_DATA = 'CLEAR_USER_SESSION_DATA',
  USER_PASSWORD_CHANGED = 'USER_PASSWORD_CHANGED',
  ACCOUNT_ALREADY_VERIFIED = 'ACCOUNT_ALREADY_VERIFIED',
}
