export enum ServerEventResponseKey {
  USER_EMAIL_NOT_VERIFIED = 'USER_EMAIL_NOT_VERIFIED',
  CURRENT_SESSION_CLOSED_BY_USER_IMPLICITLY = 'CURRENT_SESSION_CLOSED_BY_USER_IMPLICITLY',
  USER_EMAIL_ALREADY_VERIFIED = 'USER_EMAIL_ALREADY_VERIFIED',
  OTHER_USER_SESSION_CLOSED_BY_USER = 'OTHER_USER_SESSION_CLOSED_BY_USER',
  CURRENT_SESSION_CLOSED_BY_USER_EXPLICITLY = 'CURRENT_SESSION_CLOSED_BY_USER_EXPLICITLY',
}
